"""Animation engine for the VisionMoCap application.

The AnimationEngine is the bridge between retargeted motion data and the
playback/export layer.  It converts a :class:`RetargetedMotion` into an
:class:`AnimationClip` and provides frame-lookup and timing utilities.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from src.animation.animation_clip import AnimationClip
from src.animation.keyframe import InterpolationType, Keyframe
from src.animation.retargeted_motion import RetargetedMotion
from src.config.manager import AnimationConfig
from src.motion.motion_sequence import DEFAULT_FPS, is_valid_fps

_INVALID_FPS = (
    "Invalid frame rate: {value!r}. A frame rate must be a positive "
    "finite number greater than zero."
)


class AnimationEngine:
    """Creates and manages AnimationClips from retargeted motion data.

    Responsibilities:

    * Convert a :class:`RetargetedMotion` into an :class:`AnimationClip`
      with one keyframe per frame (or subsampled at a configurable rate).
    * Look up the nearest keyframe at a given timestamp.
    * Provide playback-timing helpers (duration, frame count, etc.).

    Usage::

        engine = AnimationEngine()
        clip = engine.convert(retargeted_motion)
        kf = engine.find_frame(clip, 1.5)
    """

    def __init__(
        self,
        config: Optional[AnimationConfig] = None,
    ) -> None:
        self._config = config or AnimationConfig()
        self._logger = logging.getLogger(self.__class__.__name__)

    # ------------------------------------------------------------------
    # Public API — conversion
    # ------------------------------------------------------------------

    def convert(
        self,
        motion: RetargetedMotion,
        fps: Optional[float] = None,
        interpolation: InterpolationType = InterpolationType.LINEAR,
    ) -> AnimationClip:
        """Convert a RetargetedMotion into an AnimationClip.

        Every frame in the motion becomes a keyframe in the clip.
        The *fps* parameter controls the clip's nominal frame rate;
        if omitted the motion's own ``fps`` is used.

        Args:
            motion: The retargeted motion data to convert.
            fps: Desired frame rate for the clip.  When *fps* differs
                from the motion's rate, keyframes are generated by
                sampling at the target rate.
            interpolation: Default interpolation type for keyframes.

        Returns:
            A new AnimationClip containing one keyframe per sample.

        Raises:
            ValueError: If *motion* contains no frames.
        """
        if not motion.frames:
            raise ValueError("Cannot convert an empty RetargetedMotion.")

        if fps is not None and not is_valid_fps(fps):
            raise ValueError(_INVALID_FPS.format(value=fps))

        target_fps = fps if fps is not None else (
            motion.fps if is_valid_fps(motion.fps) else DEFAULT_FPS
        )
        keyframes = self.generate_keyframes(
            motion,
            interpolation=interpolation,
            target_fps=target_fps,
        )

        clip = AnimationClip(
            keyframes=keyframes,
            duration=motion.duration,
            fps=target_fps,
            metadata={
                "source_avatar": motion.avatar_name,
                "source_fps": motion.fps,
            },
        )

        self._logger.info(
            "Converted RetargetedMotion (%d frames → %d keyframes, %.1f fps).",
            len(motion.frames),
            clip.frame_count,
            clip.fps,
        )

        return clip

    def generate_keyframes(
        self,
        motion: RetargetedMotion,
        interpolation: InterpolationType = InterpolationType.LINEAR,
        target_fps: Optional[float] = None,
    ) -> List[Keyframe]:
        """Generate keyframes from a RetargetedMotion.

        When *target_fps* is specified and differs from the motion's
        native rate, keyframes are generated by sampling at the target
        frame rate using the clip's interpolation logic.

        Args:
            motion: Source retargeted motion.
            interpolation: Default interpolation type for keyframes.
            target_fps: Desired keyframe rate.  If ``None``, every
                motion frame becomes a keyframe.

        Returns:
            A list of Keyframe objects in chronological order.
        """
        native_fps = motion.fps if is_valid_fps(motion.fps) else DEFAULT_FPS
        if target_fps is not None and not is_valid_fps(target_fps):
            raise ValueError(_INVALID_FPS.format(value=target_fps))
        effective_fps = target_fps if target_fps is not None else native_fps

        # Same rate — one keyframe per motion frame.
        if abs(effective_fps - native_fps) < 0.001:
            return [
                Keyframe(
                    timestamp=frame.timestamp,
                    frame_number=i,
                    bone_transforms=dict(frame.bones),
                    interpolation=interpolation,
                )
                for i, frame in enumerate(motion.frames)
            ]

        # Different rate — sample using a temporary clip for
        # interpolation.
        temp_clip = AnimationClip(
            keyframes=[
                Keyframe(
                    timestamp=f.timestamp,
                    frame_number=i,
                    bone_transforms=dict(f.bones),
                    interpolation=InterpolationType.LINEAR,
                )
                for i, f in enumerate(motion.frames)
            ],
            duration=motion.duration,
            fps=native_fps,
        )

        dt = 1.0 / effective_fps
        keyframes: List[Keyframe] = []
        t = 0.0
        frame_num = 0

        while t <= motion.duration + dt * 0.5:
            bones = temp_clip.interpolate(t)
            if bones is None:
                break
            keyframes.append(
                Keyframe(
                    timestamp=t,
                    frame_number=frame_num,
                    bone_transforms=bones,
                    interpolation=interpolation,
                )
            )
            t += dt
            frame_num += 1

        return keyframes

    # ------------------------------------------------------------------
    # Public API — lookup and timing
    # ------------------------------------------------------------------

    def find_frame(
        self,
        clip: AnimationClip,
        timestamp: float,
    ) -> Optional[Keyframe]:
        """Find the keyframe nearest to *timestamp*.

        Args:
            clip: The clip to search.
            timestamp: Time in seconds.

        Returns:
            The nearest Keyframe, or ``None`` if the clip is empty.
        """
        kfs = clip.keyframes
        if not kfs:
            return None
        if len(kfs) == 1:
            return kfs[0]

        # Clamp to clip bounds.
        if timestamp <= kfs[0].timestamp:
            return kfs[0]
        if timestamp >= kfs[-1].timestamp:
            return kfs[-1]

        # Linear scan (keyframe lists are small in practice).
        best = kfs[0]
        best_dist = abs(kfs[0].timestamp - timestamp)
        for kf in kfs[1:]:
            dist = abs(kf.timestamp - timestamp)
            if dist < best_dist:
                best = kf
                best_dist = dist
            else:
                break  # timestamps are sorted; distance starts increasing

        return best

    def get_playback_duration(self, clip: AnimationClip) -> float:
        """Return the effective playback duration of a clip.

        If the clip's stored duration is positive it is returned;
        otherwise the duration is computed from the last keyframe's
        timestamp.

        Args:
            clip: The animation clip.

        Returns:
            Duration in seconds.
        """
        if clip.duration > 0.0:
            return clip.duration
        kfs = clip.keyframes
        if not kfs:
            return 0.0
        return kfs[-1].timestamp
