from pathlib import Path
from datetime import datetime
from typing import List, Optional


def generate_project_status(project_root: Path) -> str:
    version = _read_version(project_root)
    features_done, features_total = _count_roadmap_items(project_root / "ROADMAP.md")
    known_bugs = _count_bugs(project_root / "KNOWN_BUGS.md")
    test_count = _count_tests(project_root / "tests")

    return f"""# Project Status

*Auto-generated by visionmocap-ai on {datetime.now().strftime("%Y-%m-%d %H:%M")}*

## Current Version
{version}

## Completed Features
{features_done} / {features_total} roadmap items completed

## Known Bugs
{known_bugs} documented

## Test Coverage
{test_count} test files found

## Next Steps
See [ROADMAP.md](ROADMAP.md) for upcoming milestones.
"""


def _count_bugs(path: Path) -> int:
    try:
        content = path.read_text(encoding="utf-8")
        return content.count("- [ ]") + content.count("- [x]")
    except (FileNotFoundError, Exception):
        return 0


def _count_tests(path: Path) -> int:
    return len(list(path.rglob("test_*.py")))


def _read_version(project_root: Path) -> str:
    changelog = project_root / "CHANGELOG.md"
    try:
        content = changelog.read_text(encoding="utf-8")
        for line in content.splitlines():
            if line.startswith("## [") and "Unreleased" not in line:
                return line.strip("## []").strip()
    except (FileNotFoundError, Exception):
        pass
    return "0.0.0"


def _count_roadmap_items(path: Path):
    done = 0
    total = 0
    try:
        content = path.read_text(encoding="utf-8")
        for line in content.splitlines():
            if "- [x]" in line:
                done += 1
                total += 1
            elif "- [ ]" in line:
                total += 1
    except (FileNotFoundError, Exception):
        pass
    return done, total


def _read_version(project_root: Path) -> str:
    changelog = project_root / "CHANGELOG.md"
    try:
        content = changelog.read_text(encoding="utf-8")
        for line in content.splitlines():
            if line.startswith("## [") and "Unreleased" not in line:
                return line.strip("## []").strip()
    except (FileNotFoundError, Exception):
        pass
    return "0.0.0"


def generate_changelog_entry(version: str, changes: List[str]) -> str:
    date = datetime.now().strftime("%Y-%m-%d")
    lines = [f"\n## [{version}] — {date}\n"]
    lines.append("### Added")
    for change in changes:
        lines.append(f"- {change}")
    lines.append("")
    return "\n".join(lines)


def generate_tasks(project_root: Path) -> str:
    roadmap = project_root / "ROADMAP.md"
    try:
        content = roadmap.read_text(encoding="utf-8")
    except (FileNotFoundError, Exception):
        content = ""

    lines = ["# Tasks", "", "*Auto-generated by visionmocap-ai*", ""]
    current_section = None
    for line in content.splitlines():
        if line.startswith("## "):
            current_section = line.strip("# ").strip()
            lines.append(f"## {current_section}")
        elif line.strip().startswith("- [ ]"):
            task = line.strip("- [ ]").strip()
            lines.append(f"- [ ] {task}")
        elif line.strip().startswith("- [x]"):
            task = line.strip("- [x]").strip()
            lines.append(f"- [x] {task}")

    return "\n".join(lines)


def generate_known_bugs(project_root: Path) -> str:
    arch_rules = project_root / ".ai" / "architecture-rules.md"
    known = []
    try:
        content = arch_rules.read_text(encoding="utf-8")
        in_section = False
        for line in content.splitlines():
            if "Known issues" in line:
                in_section = True
                continue
            if in_section and line.startswith("## "):
                break
            if in_section and line.strip().startswith(("1.", "2.", "3.", "4.", "5.", "6.")):
                known.append(line.strip())
    except (FileNotFoundError, Exception):
        pass

    lines = [
        "# Known Bugs",
        "",
        f"*Auto-generated by visionmocap-ai on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
    ]
    if known:
        for i, bug in enumerate(known, 1):
            lines.append(f"{i}. {bug.lstrip('0123456789.').strip()}")
    else:
        lines.append("No known bugs documented.")
    lines.append("")
    return "\n".join(lines)


def generate_test_plan(project_root: Path) -> str:
    test_files = list((project_root / "tests").rglob("test_*.py"))
    src_files = list((project_root / "src").rglob("*.py"))

    lines = [
        "# Test Plan",
        "",
        f"*Auto-generated by visionmocap-ai on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        "## Test Files",
        "",
    ]
    for tf in sorted(test_files):
        rel = tf.relative_to(project_root)
        lines.append(f"- {rel}")
    lines.append("")
    lines.append(f"**Total: {len(test_files)} test files**")
    lines.append("")

    modules_without_tests = _find_modules_without_tests(project_root)
    if modules_without_tests:
        lines.append("## Modules Without Tests")
        for m in modules_without_tests:
            lines.append(f"- {m}")
        lines.append("")

    return "\n".join(lines)


def _find_modules_without_tests(project_root: Path) -> List[str]:
    src_modules = set()
    for p in (project_root / "src").rglob("*.py"):
        if p.stem != "__init__":
            rel = p.relative_to(project_root / "src")
            src_modules.add(str(rel.with_suffix("")))

    test_modules = set()
    for p in (project_root / "tests").rglob("test_*.py"):
        name = p.stem.replace("test_", "", 1)
        test_modules.add(name)

    return sorted(m for m in src_modules if m not in test_modules)


def _read_version(project_root: Path) -> str:
    changelog = project_root / "CHANGELOG.md"
    try:
        content = changelog.read_text(encoding="utf-8")
        for line in content.splitlines():
            if line.startswith("## [") and "Unreleased" not in line:
                return line.strip("## []").strip()
    except (FileNotFoundError, Exception):
        pass
    return "0.0.0"


def _count_roadmap_items(path: Path):
    done = 0
    total = 0
    try:
        content = path.read_text(encoding="utf-8")
        for line in content.splitlines():
            if "- [x]" in line:
                done += 1
                total += 1
            elif "- [ ]" in line:
                total += 1
    except (FileNotFoundError, Exception):
        pass
    return done, total


def _read_version(project_root: Path) -> str:
    changelog = project_root / "CHANGELOG.md"
    try:
        content = changelog.read_text(encoding="utf-8")
        for line in content.splitlines():
            if line.startswith("## [") and "Unreleased" not in line:
                return line.strip("## []").strip()
    except (FileNotFoundError, Exception):
        pass
    return "0.0.0"

