from typing import List, Dict, Any
from datetime import datetime


def generate_review_report(findings: List[dict]) -> str:
    lines = [
        "# Code Review Report",
        "",
        f"*Generated by visionmocap-ai on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        "## Summary",
        "",
    ]

    by_type: dict[str, list[dict]] = {}
    for f in findings:
        by_type.setdefault(f["type"], []).append(f)

    total = len(findings)
    lines.append(f"**Total issues found: {total}**")
    lines.append("")

    type_labels = {
        "duplicated_code": "Duplicated Code",
        "dead_code": "Dead Code",
        "architecture_violation": "Architecture Violations",
        "missing_docstring": "Missing Documentation",
        "missing_test": "Missing Tests",
        "large_class": "Large Classes",
        "large_method": "Large Methods",
        "unused_import": "Unused Imports",
        "todo": "TODO Comments",
        "fixme": "FIXME Comments",
    }

    for key, label in type_labels.items():
        items = by_type.get(key, [])
        if items:
            lines.append(f"### {label} ({len(items)})")
            lines.append("")
            for item in items[:10]:
                if key == "duplicated_code":
                    locs = item.get("locations", [])
                    lines.append(f"- Block: `{item['block']}`")
                    for f, l in locs:
                        lines.append(f"  - {f}:{l}")
                elif key == "dead_code":
                    lines.append(f"- `{item['name']}` at `{item['file']}:{item['line']}`")
                elif key == "architecture_violation":
                    lines.append(f"- {item['detail']} at `{item['file']}:{item['line']}`")
                elif key == "missing_docstring":
                    lines.append(f"- `{item['name']}` at `{item['file']}:{item['line']}`")
                elif key == "missing_test":
                    lines.append(f"- `{item['file']}` — expected `{item['expected_test']}`")
                elif key in ("large_class", "large_method"):
                    lines.append(f"- `{item['name']}` at `{item['file']}:{item['line']}` ({item['lines']} lines)")
                elif key == "unused_import":
                    lines.append(f"- `{item['name']}` at `{item['file']}:{item['line']}`")
                elif key in ("todo", "fixme"):
                    lines.append(f"- `{item['text']}` at `{item['file']}:{item['line']}`")
            lines.append("")

    return "\n".join(lines)
